### ISSUE TITLE
Error on ComfyUI Manager 

### ISSUE THREAD

**Issue by josigamer** [LykosAI/ComfyUI-Inference-Core-Nodes#12]
![Captura de tela 2024-03-26 200120](https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes/assets/50076918/833d59a4-23b6-4b12-b7e5-c687579b4e54)

I'm getting this error message, I've tried reinstalling and it doesn't work

**Comment by LeoMK01** [comment]
same

**Comment by krasteriii** [comment]
trying to install from the extension manager gives this result:

Cloning https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'ComfyUI-Inference-Core-Nodes'...
fatal: cannot create directory at 'src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/depth_anything/torchhub/facebookresearch_dinov2_main/dinov2/configs/eval': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Helper.IPrerequisiteHelper.CloneGitRepository(String rootDir, String repositoryUrl, GitVersion version)
   at StabilityMatrix.Core.Models.Packages.Extensions.GitPackageExtensionManager.InstallExtensionAsync(PackageExtension extension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.InstallExtensionAsync(PackageExtension extension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by Serpens66** [comment]
this should fix it:
https://katalon-inc.my.site.com/katalonhelpcenter/s/article/How-to-fix-Git-Clone-Filename-too-long-Error-in-Windows
So I as a user did:

> 1. Git Global Level
> 
> Please follow the steps below to fix "Filename is too long" in Git.
> 
>     Update to the newest version of git. If you have already upgraded, skip this step.
> 
>     Navigate to your project folder
> 
>     Open the Git Bash and run it as an administrator
> 
>     To enable long paths in Git Bash, use "git config --system core.longpaths true"
> 
> Now clone the project with longer filenames that should no longer generate a problem. This solution mostly works for users to fix the issue. It is applicable to all repositories that will be cloned for future projects.

**Comment by dkampien** [comment]
I have the same problem. I tried the fix above and it didn't work.

**Comment by WeirdScienceX** [comment]
Same, it's the only one I consistently have issues with

**Comment by GoooIce** [comment]
The problem seems to originate from the installation of mediapipe.Need python 3.7-11

**Comment by GoooIce** [comment]
if you want install this with python3.12 for now [2024.4.10]. just try:

1. download `mediapipe-0.10.11-cp311-cp311-win_amd64.whl` from pypi site
2. rename it to `mediapipe-0.10.11-cp312-cp312-win_amd64.whl`
3. pip install
4. edit `custom_nodes\ComfyUI-Inference-Core-Nodes\pyproject.toml` line 9: `requires-python = ">=3.10,<=3.13"`
5. run `python install.py`

enjoy...

**Comment by githubarooski** [comment]
> if you want install this with python3.12 for now [2024.4.10]. just try:
> 
>     1. download `mediapipe-0.10.11-cp311-cp311-win_amd64.whl` from pypi site
> 
>     2. rename it to `mediapipe-0.10.11-cp312-cp312-win_amd64.whl`
> 
>     3. pip install
> 
>     4. edit `custom_nodes\ComfyUI-Inference-Core-Nodes\pyproject.toml` line 9: `requires-python = ">=3.10,<=3.13"`
> 
>     5. run `python install.py`
> 
> 
> enjoy...

If I just re-name it like you suggest, I get an error that it's not a supported wheel

```
PS D:\Documents\stable-diffusion\stableswarmui\StableSwarmUI\dlbackend\comfy\ComfyUI> ..\python_embeded\python.exe -m pip install .\mediapipe-0.10.11-cp312-cp312-win_amd64.whl
ERROR: mediapipe-0.10.11-cp312-cp312-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by Zoobyai** [comment]
Managed to fix this on my end on a portable Windows install, it seems like filename too long error allowed to set up a broken dependency chain which had to be manually re-installed. Setting "git config --system core.longpaths true" allowed an install to complete but did not fix the root issue on Windows, as Windows appends file locations that exceed the default limit with `"\\?\"` which then breaks some of the dependency references that are set up with an absolute path that does not include the prefix. This then allowed a broken install of dependencies that created only the .dist-info files and not the python files themselves for some of the dependencies, and for others broke references made within the dependencies themselves.

Additionally, Im using the portable version of comfyUI, and the pip dependencies seem to install to a default python env in the root drive under `X:\python\Lib\site-packages` and not `ComfyUI_windows_portable\python_embeded\Lib\site-packages`.

The fix that worked for me was 
1) shortening the amount of characters in the filepath (simply renaming the top level folder from the default wordy folder name to simply "comfyUI", it helped that my comfyUI install is in a folder in the top level of a drive)
2) uninstalling and re-installing the dependencies;
- In command prompt, navigate to the `ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes>` folder
- `pip uninstall -y inference_core_nodes`
- `pip install . -vvv`
- this will show you all the requirements that have been installed, dont be fooled by "requirement already met" some of these will likely be broken installs
- pip uninstall again
- `pip uninstall` all of the installed requirements listed in the previous step
- do another fresh install using `pip install . -vvv`
- copy all of the files under  `X:\python\lib\site-packages` into `ComfyUI_windows_portable\python_embeded\Lib\site-packages`

As long as the filepaths are still not too long, this should correct the python dependency chain that creates this error.

**Comment by iamlkq** [comment]
same

**Comment by arvinsim** [comment]
I have the same problem too on a windows 11 machine.

I tried the enable long paths fix but it didn't work for me.
