### ISSUE TITLE
ModuleNotFoundError: No module named 'inference_core_nodes.controlnet_preprocessors.utils'

### ISSUE THREAD

**Issue by gerroon** [LykosAI/ComfyUI-Inference-Core-Nodes#19]
Hi

How can I fix this error?

Windows 11, ComfyUI: 2205[58c983](2024-05-24) Manager: V2.35.1

```
Config Export Error[Errno 2] No such file or directory: 'XXXHOST-PATHXXX\\PATH_CFG.json'### Loading: ComfyUI-Impact-Pack (V5.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\__init__.py", line 57, in <module>
    NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS = _get_node_mappings()
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\__init__.py", line 36, in _get_node_mappings
    submodule = importlib.import_module(f"{__name__}.{submodule_info.name}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\controlnet_preprocessors\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
ModuleNotFoundError: No module named 'inference_core_nodes.controlnet_preprocessors.utils'

```

**Comment by andycuccaro** [comment]
I'm facing the same error, also on Windows 11. I don't know if it matters, but I have installed the portable version of ComfyUI (downloaded from here: https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_or_cpu.7z).

**Comment by belgriffinite** [comment]
I also have this issue, did anyone find a fix?
