### ISSUE TITLE
Error when install Inference Core Nodes

### ISSUE THREAD

**Issue by danghuong18** [LykosAI/ComfyUI-Inference-Core-Nodes#9]
I get this error when install Inference Core Nodes, please help me fix this. Thanks

```
[!] ERROR: Exception:
[!] Traceback (most recent call last):
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
[!]     status = run_func(*args)
[!]              ^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
[!]     return func(self, options, args)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
[!]     requirement_set = resolver.resolve(
[!]                       ^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
[!]     collected = self.factory.collect_root_requirements(root_reqs)
[!]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 534, in collect_root_requirements
[!]     reqs = list(
[!]            ^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 490, in _make_requirements_from_install_req
[!]     cand = self._make_base_candidate_from_link(
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 207, in _make_base_candidate_from_link
[!]     self._editable_candidate_cache[link] = EditableCandidate(
[!]                                            ^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in __init__
[!]     super().__init__(
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
[!]     self.dist = self._prepare()
[!]                 ^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
[!]     dist = self._prepare_distribution()
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 325, in _prepare_distribution
[!]     return self._factory.preparer.prepare_editable_requirement(self._ireq)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 696, in prepare_editable_requirement
[!]     dist = _get_prepared_distribution(
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
[!]     abstract_dist.prepare_distribution_metadata(
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 52, in prepare_distribution_metadata
[!]     self.req.isolated_editable_sanity_check()
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_install.py", line 545, in isolated_editable_sanity_check
[!]     and not self.supports_pyproject_editable()
[!]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_install.py", line 257, in supports_pyproject_editable
[!]     return "build_editable" in self.pep517_backend._supported_features()
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 153, in _supported_features
[!]     return self._call_hook('_supported_features', {})
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
[!]     raise BackendUnavailable(data.get('traceback', ''))
[!] pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[!]   File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
[!]     obj = import_module(mod_path)
[!]           ^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "importlib\__init__.py", line 126, in import_module
[!]   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
[!]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[!]   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
[!] ModuleNotFoundError: No module named 'flit_core'
[!]
[!] Traceback (most recent call last):
[!]   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 38, in <module>
[!]     main()
[!]   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 29, in main
[!]     pip_install(["-e", ".[cuda-12]"])
[!]   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 11, in pip_install
[!]     subprocess.check_call(
[!]   File "subprocess.py", line 413, in check_call
[!] subprocess.CalledProcessError: Command '['E:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', '-e', '.[cuda-12]']' returned non-zero exit status 2.
install/(de)activation script failed: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
```

**Comment by bruibbruib** [comment]
same issue.

**Comment by shuchong** [comment]
pip install flit-core
